### PR TITLE
Mob Vote logo textures

### PR DESCRIPTION
**Pull request by GoldNinja10**
Minecraft Five Bold textures based on the Minecon Mob Vote logo. 
MV_title

The "O" isn't a square creeper face though, to follow the font shape rules.

### CODE REVIEW

**Comment by blank3times** [comment]
Mr. Howell, would it be acceptable to have a texture variant with a rounded O creeper face? In theory that doesn't affect the border if it's rounded.

**Comment by GoldNinja10** [comment]
> In theory that doesn't affect the border if it's rounded.

the island in the center counts as a border, so it still wouldn't work out unfortunately. the font itself would need to be different.
minecraft_title (22)

**Comment by blank3times** [comment]
I see. I forgot the font is wider than MC-10. That's unfortunate.

**Comment by ewanhowell5195** [comment]
missing closing bracket. i will add it for you

**Pull request merged**
