### PR TITLE
Dock Texture

### PR DESCRIPTION
**Pull request by RyanCR03**
Added texture "Dock" based off of the first minecraft logo design by Hayden "Dock" Scott-Baron.
1 Variant: Dock (Clear).

### CODE REVIEW

**Comment by RyanCR03** [comment]
I accidentally uploaded the clear variant twice... oops

**Comment by ewanhowell5195** [comment]
what is dock clear?

**Comment by ewanhowell5195** [comment]
ah ok

**Comment by RyanCR03** [comment]
dock
this is supposed to be the regular dock

**Comment by ewanhowell5195** [comment]
can you add it to the PR then? just delete the old file in your fork and upload this one

**Comment by RyanCR03** [comment]
i gotta figure out how... ive never done a pull request

**Comment by RyanCR03** [comment]
Thanks!

**Pull request merged**
