### PR TITLE
Steel Texture

### PR DESCRIPTION
**Pull request by DoharCraft**
Adds steel/metalic texture kinda like platinum.

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
your JSON is invalid. you added it outside of the textures.

**Comment by DoharCraft** [comment]
> your JSON is invalid. you added it outside of the textures.

oh wait, Lemme fix it

**Comment by DoharCraft** [comment]
ugh, I can't seem to fix the json, could you please?

**Comment by DoharCraft** [comment]
okay, I think I fixed it. Lol.

**Pull request merged**
