### PR TITLE
Added wool textures

### PR DESCRIPTION
**Pull request by Splatube**
White wool and 15 color variants

### CODE REVIEW

**Comment by Splatube** [comment]
Added a white wool texture for the minecraft ten font and 15 other color variants

**Comment by ewanhowell5195** [comment]
tiling and overlaying a minecraft texture over the letters is a low effort submittion.

**Comment by DoharCraft** [comment]
@ewanhowell5195 I would highly suggest merging this, Even if its a *low effort* submission, its still a quality full texture with variants.

**Comment by ewanhowell5195** [comment]
classic cobblestone is based on an official minecraft logo. it gets an exception.

i can tell that this texture was done lazily by just tiling the texture over it because the textures do not even line up with lots of the characters. The pixels get cut in half by the edges of the character, which means that no thought was put into actually lining it up nicely.

image
image
image
image

If you want to go and make a better version of this where the pixels actually line up with the characters properly, you are more than welcome to

**Pull request closed without merging**
