### PR TITLE
Add cyrillic version of old cracked

### PR DESCRIPTION
**Pull request by EJYozhenka**
cracked_old копия

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
there is a random line of pixels on the bottom of the `ж` character
image

other than that looks good. can you fix this small thing, thanks.

also your JSON is invalid. you need to add a comma on the line before the bit you added, and close the brackets that you opened. use https://jsonlint.com/ to validate it

**Comment by EJYozhenka** [comment]
I fixed it

**Comment by ewanhowell5195** [comment]
you have now changed the whole formatting of the file. please leave it how it was, and only add your new stuff to it
image

**Comment by EJYozhenka** [comment]
Fixed it. Most likely jsonlint changed the formatting, but I didn’t pay attention

**Pull request merged**
