### PR TITLE
Added Podzol, Mycelium, Crimson Nylium and Warped Nylium

### PR DESCRIPTION
**Pull request by oliviathevampire**

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
These are just recolours of grass. If you want to add textures, please be create unique designs for each one, and not recolour existing ones.

**Comment by oliviathevampire** [comment]
So that means that you do not accept recolors? like for example different planks?

**Comment by ewanhowell5195** [comment]
i do not want this plugin being spammed with recolours of existing textures. it is not hard to open a texture in an image editor and change the colours yourself, if the built-in styles do not give the result you are looking for. it is just lazy, and extra clutter in between the actual unique designs.

**Comment by oliviathevampire** [comment]
Maybe a thing that could work, is if even possible, have when clicked on an icon on the ones which could have multiple variants it would open another screen or something with the variants, so it's not all clutter, but I do understand. Gonna try and make these more unique

**Comment by ewanhowell5195** [comment]
added variants. coming in next update. I have added your plank textures as examples. if they are not finished you can update them

**Pull request closed without merging**
