### PR TITLE
Adds a texture that looks like the Trails & Tales update title.

### PR DESCRIPTION
**Pull request by evisnoopy**
This could not be done with the basic gradient function because the top face is an entirely different color than the top of the front. Not a perfect recreation because there are gradients coming in from the left and right of the official title which can not be applied through a font.

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
while I would normally reject something like this, because "the top face is an entirely different color than the top of the front", since you can use the plugin to change that in the style tab, I will allow it as it is on theme of an update title.

however first you need to fix the texture ID as it does not follow the rules specified in the readme

**Comment by ewanhowell5195** [comment]
also maybe you should add the & being unique, just like in the actual update logo @evisnoopy

**Comment by ewanhowell5195** [comment]
@evisnoopy could you make the requested change please?

**Comment by louanfontenele** [comment]
@evisnoopy I saw that you added a variant for the `&` symbol. it would be interesting to have this same variant for the letters, to also have a lighter tone. It could separate between uppercase and lowercase letters. If you put the letters in uppercase it is in the dark tone, if it is lowercase it is in the light tone. I don't know if I explained it right, but that's the idea.

**Comment by ewanhowell5195** [comment]
use the gradient generator to create a gradient of your choice.

**Pull request merged**
