### PR TITLE
Bricks Textures

### PR DESCRIPTION
**Pull request by IIAmMaker**

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
your textures.json file is invalid. you are missing a closing }

**Comment by IIAmMaker** [comment]
> your textures.json file is invalid. you are missing a closing }

I fix it

**Comment by ewanhowell5195** [comment]
https://jsonlint.com/

**Comment by IIAmMaker** [comment]
> https://jsonlint.com/

**Comment by IIAmMaker** [comment]
> https://jsonlint.com/

"Valid JSON"

**Pull request closed without merging**
