### PR TITLE
Haunted texture

### PR DESCRIPTION
**Pull request by Ninjaabdullah**
Adds Haunted texture

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
your texture is lower down for the characters on the bottom row, so it doesn't line up properly
image

your texture name does not match the provided id

**Comment by Ninjaabdullah** [comment]
Fixed Bottom row textures and Resolved unmatched name with ID
I don't know if I have to sync forks though

**Comment by ewanhowell5195** [comment]
sorry for the late reply. one last thing: your V uv is wrong. please update it to match with the latest flat.png

**Comment by Ninjaabdullah** [comment]
No worries.
Updated "V" uv to match with the latest flat.png

**Pull request merged**
