### PR TITLE
Sign and curilic

### PR DESCRIPTION
**Pull request by Bitsek**

### CODE REVIEW

**Comment by blank3times** [comment]
You don't have to add `cyrillic` (`curilic`) to the texture names since it's in a different folder (it's actually preferred that you remove that. Advising you so you can fix it before Ewan sees it =]

**Comment by ewanhowell5195** [comment]
Please call them `planks` instead of `sign` to be consistent with the other fonts

**Comment by ewanhowell5195** [comment]
in cyrillic five bold, your planks textures last row does not line up with the other character rows
image

you also have some characters that just do not line up with the actual character models
image
image

**Comment by ewanhowell5195** [comment]
if you are adding textures from other fonts, please be consistent with their naming.

in minecraft-ten-cyrillic
```json
    "flat_color": {
      "flat (coloured)",
      "author": "BitseK & TheAnnoying"
    },
```
this should have the ID of `flat_coloured` the name field should not be provided for this one

**Comment by ewanhowell5195** [comment]
image
please capitalise your names
please change the ids to `glass_old` and `glass_tempered` so that the files are alphabetically next to eachother

**Comment by ewanhowell5195** [comment]
minecraft-ten textures.json has invalid json. please use a json checker https://jsonlint.com/

**Comment by ewanhowell5195** [comment]
closing this pull request. delete your fork and refork it, then only add one change. after that is merged, then you can add another change and make another pull request. this PR simply has too many things in it for you to manage in one go

**Pull request closed without merging**
