### PR TITLE
Minecraft Five Bold Cyrillic

### PR DESCRIPTION
**Pull request by xlifi**
At the time editing this message, font is fully done

"Debug" is intentionally unlisted. Apply manually to check top/bottom face orientations. Delete it when everything's ready, edits by maintainers are allowed

### CODE REVIEW

**Comment by ImNotSawiq** [comment]
cool

**Comment by xlifi** [comment]
>"Debug" is intentionally unlisted. Apply manually to check top/bottom face orientations
 
 Delete "debug" texture when everything's ready, edits by maintainers are allowed

**Comment by ewanhowell5195** [comment]
The down faces on the backwards N characters are there when they should be set to none, can you fix this please.

could you also remove any pixels in the outline that are not used
image

you are also missing ₽
image

**Comment by ewanhowell5195** [comment]
Some characters faces on the bottom are the wrong orientation
image

**Comment by xlifi** [comment]
> The down faces on the backwards N characters are there when they should be set to none, can you fix this please.

I didn't understand what you mean by that. Everything else you mentioned is fixed

**Comment by ewanhowell5195** [comment]
the down faces of the extra cubes at the bottom are transparent and set to the top left of the UV map

**Comment by ewanhowell5195** [comment]
please remove debug from the final commit

**Comment by xlifi** [comment]
This is ready to merge for a week now

**Comment by ewanhowell5195** [comment]
> could you also remove any pixels in the outline that are not used image

you didnt fix the outline

**Comment by xlifi** [comment]
I did fix outlines and faces, but forgot to compile. Check again now

**Comment by xlifi** [comment]
Outlines are fixed in [6064835](https://github.com/ewanhowell5195/MinecraftTitleGenerator/pull/90/commits/606483546a685ffc0dcc0cad080de8bbd3a839b7)
И, Й faces are fixed in [3c38261](https://github.com/ewanhowell5195/MinecraftTitleGenerator/pull/90/commits/3c3826163990a67192a63bd58fe061d2c94c8251)

That's compiled in [a5a0fd7](https://github.com/ewanhowell5195/MinecraftTitleGenerator/pull/90/commits/a5a0fd79c6b76e34d67f9811c09a05f9df14b34d)

**Pull request merged**
