### PR TITLE
Adds pride flag textures.

### PR DESCRIPTION
**Pull request by SnuzzleWump**
I have not compiled it and it is very possible that i haven't edited the textures.json properly.

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
please change the ones with solid black to use a dark grey instead, as it looks bad in logos

**Comment by ewanhowell5195** [comment]
the details of the letters get hidden in the pure black
image

**Comment by ewanhowell5195** [comment]
also on enby there are missing pixels in the comma top
image

**Comment by ewanhowell5195** [comment]
example of updated enby
image

**Comment by SnuzzleWump** [comment]
I think I have fixed both of those issues now.

**Comment by ewanhowell5195** [comment]
your gay and lesbian flags seem to have different numbers of colours. is this intentional? i googled it and they both seem to have 5 and 7 colour variants. maybe its best to make them the same in the plugin?

**Comment by SnuzzleWump** [comment]
I have changed the lesbian flag to have the 7 colour flag.

lesbian
lesbian

**Comment by SnuzzleWump** [comment]
I've also just realised that I didn't upload pansexual.

pansexual
pansexual

**Comment by ewanhowell5195** [comment]
please create a new PR adding these. also someone wanted the hetrosexual flag added too. could you do that?

**Comment by SnuzzleWump** [comment]
yes I can do that, do you know which one they wanted? as there are many different ones including these:

400px-Heterosexual_flag_(black-white_stripes) svg
latest-2483181521
Straight_Ally_flag svg

**Comment by ewanhowell5195** [comment]
i think it was this one:
image

**Pull request merged**
