### PR TITLE
Add trails and tales Cyrillic texture

### PR DESCRIPTION
**Pull request by RGameRG**
texture port from Latin to Cyrillic

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
this is not accurate to the latin texture. please fix this

**Comment by RGameRG** [comment]
What do you mean? Do you mean that I didn't exactly port the texture to Cyrillic? Or what?

**Comment by ewanhowell5195** [comment]
the highlights do not match

**Comment by ewanhowell5195** [comment]
please fix this, or i will be closing this pull request

**Comment by ewanhowell5195** [comment]
closing as author is unresponsive

**Pull request closed without merging**
