### PR TITLE
Add Cherry Blossom (Small) Variant

### PR DESCRIPTION
**Pull request by NotAGanesh**

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
IDs are not allowed brackets. should be `cherry_blossom_small`
Your JSON is invalid. Missing a comma and 2 closing brackets

**Comment by NotAGanesh** [comment]
> IDs are not allowed brackets. should be `cherry_blossom_small` Your JSON is invalid. Missing a comma and 2 closing brackets

Now check

**Comment by ewanhowell5195** [comment]
Use https://jsonlint.com/ to validate the JSON. it is still invalid
You are still missing a comma and 2 closing brackets.
it should be like this
image

**Comment by ewanhowell5195** [comment]
also please add a space before `(Small)`

**Comment by ewanhowell5195** [comment]
and you need to add in the author to credit yourself

**Comment by NotAGanesh** [comment]
Now check

**Comment by ewanhowell5195** [comment]
i showed you in a screenshot how it should be and it is still wrong. Also put `small` back in brackets

it should be
```json
    "cherry_blossom": {
      "author": "Klayv",
      "variants": {
        "cherry_blossom_small": {
          "name": "Cherry Blossom (Small)",
          "author": "NotAGanesh"
        }
      }
    }
```

**Comment by NotAGanesh** [comment]
hey dude can you code please, because i'm not an developer/coder

**Comment by ewanhowell5195** [comment]
literally just copy paste the bit i just sent into it. revert it back to the original first as you deleted some other stuff

**Comment by NotAGanesh** [comment]
sorry last time check

**Pull request merged**
