### PR TITLE
Many different textures

### PR DESCRIPTION
**Pull request by MCAlexisYT**
List of the textures:

1. Pastel. The same textures except the smeared variant as it got rejected.
2. Netherite (MC5). Doesn't include the gilded variant of the MC10 variant.
3. Pac-man Maze (MC5) When I saw the Dots texture, I saw the opportunity for a texture inspired by the [Pac-Man video game](https://en.wikipedia.org/wiki/Pac-Man), and this is the result. Used the Dots texture as a base, hue-shifted it to blue and did a few other adjustments.

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
Neon glow was removed from five bold block because it is not seamless.
image
I asked you to fix this in #84 but it is still not fixed

Pastel is just a gradient with the outline overlay, please remove that.

Packman Maze is just a recolour of dots, please remove that

Your JSON is also invalid, please fix that.

Due to the number of changes required, please open a new PR with just the netherite texture commited in it, since that is the only texture here that is allowed.

**Comment by MCAlexisYT** [comment]
Pac-Man Maze has the insides darkened.
pacman-maze

**Comment by ewanhowell5195** [comment]
yes, thats what recolour means

**Comment by MCAlexisYT** [comment]
Guess I'll have to pull a "[ThioJoe creating a tool for mass-deleting spam comments on Youtube](https://youtu.be/-vOakOgYLUI?si=xjY-w6mCHS6pAqzi)" moment and create the texture myself.

**Comment by MCAlexisYT** [comment]
...or maybe not.

**Pull request closed without merging**
