### PR TITLE
Poison Texture

### PR DESCRIPTION
**Pull request by Doharbdjr**
Adds a subtle yellow poison texture for Minecraft Ten.
Preview:
image

### CODE REVIEW

**Comment by blank3times** [comment]
Looks like you used atmosphere and adjusted the hue/saturation/brightness/contrast. Maybe you gave it a custom border? But Ewan will rule that type of submission out. (Don't be too surprised if it happens)

**Comment by Doharbdjr** [comment]
I just noticed it oddly looks similar to atmosphere version. Wait lemme fix that up 😂

**Comment by Doharbdjr** [comment]
How'd this look?
image

**Comment by ewanhowell5195** [comment]
"Do not submit textures generated using the plugin."

This texture is just solid green with the glass overlay

**Pull request closed without merging**
