### PR TITLE
add bevelled gold (latin texture by CL697 & ShrimpSnail)

### PR DESCRIPTION
**Pull request by jackeyrolz**

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
why is atmosphere included in this pull request

**Comment by jackeyrolz** [comment]
idk, didn't change the texture files

**Comment by jackeyrolz** [comment]
deleted unwanted commits :D

**Comment by ewanhowell5195** [comment]
image

these bits are not shaded correctly

**Comment by jackeyrolz** [comment]
there are a lot more issues here, i'll fix them soon

**Comment by ewanhowell5195** [comment]
also these edges are incorrect (highlighted pink to make more obvious) 
image
image
image
image
image

**Comment by ewanhowell5195** [comment]
image
top left corner of this

**Comment by ewanhowell5195** [comment]
image
missing highlight on top left

**Comment by ewanhowell5195** [comment]
dont make any changes to the original texture

**Comment by ewanhowell5195** [comment]
image
pixel error here

**Comment by jackeyrolz** [comment]
okay thank you

**Comment by jackeyrolz** [comment]
texture is fixed

**Comment by jackeyrolz** [comment]
texture and thumbnail are updated

**Pull request merged**
