### PR TITLE
Neon textures for every other font

### PR DESCRIPTION
**Pull request by MCAlexisYT**
Literally adds neon textures to every font other than Minecraft Ten.

Also, for some reason, random overlays have been changed, probably due to `compile.js` screwing around with unrelated stuff.

### CODE REVIEW

**Comment by MCAlexisYT** [comment]
The random overlay thumbnails that have been changed look the same, though. Whoever did those probably did the thumbnail work manually.

**Comment by ewanhowell5195** [comment]
Please fix the line terminators in ten outline

**Comment by MCAlexisYT** [comment]
I just fixed it

**Comment by ewanhowell5195** [comment]
Please could you fix the neon glow texture for five bold block
image
the glow should completely dissapate before it reaches the edge of the characters so that it does not have a hard cutoff. alternatively make the glow inside the characters instead

**Comment by ewanhowell5195** [comment]
@MCAlexisYT i have removed this texture until it is fixed, since it does not meet the expected quality requirements

**Pull request merged**
