### PR TITLE
Flowers Side texture

### PR DESCRIPTION
**Pull request by MStankiewiczOfficial**
I connected Flowers and Grass Side textures to create Flowers Side texture.

Here is a preview:
Flowers Side texture preview

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
remove the flowers where the dirt is it doesn't make sense for them to be there

**Comment by ewanhowell5195** [comment]
Change the author to just yourself

**Comment by MStankiewiczOfficial** [comment]
Fixed :)

**Comment by ewanhowell5195** [comment]
your borders are sometimes making petals green instead of the correct colour. please fix this

the red petal in the middle for example
image

should be

image

**Comment by ewanhowell5195** [comment]
random dot on B
image

missing corner on D
image

missing highlights on P
image

random dot on W
image

large dirt pixel not aligned with pixel grid (if this is on the other textures too could you fix those as well thx)
image

random dot in %
image

**Comment by ewanhowell5195** [comment]
Sorry, just noticed the issue with large pixels not aligned with the pixel grid is also present on a bunch of other textures. could you fix those too. thanks

A C H J L M N T

**Comment by ewanhowell5195** [comment]
@MStankiewiczOfficial

**Comment by ewanhowell5195** [comment]
why did you close this it was nearly finished?

**Pull request closed without merging**
