### PR TITLE
starry night

### PR DESCRIPTION
**Pull request by HARYA301**

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
you added back in the other two textures that were rejected

**Comment by ewanhowell5195** [comment]
your JSON structure is also invalid

**Comment by ewanhowell5195** [comment]
https://jsonlint.com/

**Comment by HARYA301** [comment]
I don't see the issue tbf

**Comment by ewanhowell5195** [comment]
Sorry but I have changed my mind about this texture and will remove it. There is already a stars texture, and this one doesn't look very good.

**Pull request merged**
