### PR TITLE
Sniffer Title

### PR DESCRIPTION
**Pull request by SmarterCob**
minecraft_title2
What do you think of this?

### CODE REVIEW

**Comment by ewanhowell5195** [comment]
too dark, make it brighter

**Comment by HiBoiDudu** [comment]
Sure thing, how does this look?
brightsniffer

**Comment by HiBoiDudu** [comment]
Or is that too bright?

**Comment by ewanhowell5195** [comment]
much better

**Comment by HiBoiDudu** [comment]
Alright, do I need to send in the new, brighter texture for it?

**Comment by HiBoiDudu** [comment]
Oh wait hold on, Ill just put it in the fork I made

**Comment by HiBoiDudu** [comment]
Done.

**Comment by ewanhowell5195** [comment]
in future, please do not use capital letters in the id

**Pull request merged**
