### PR TITLE
Cherry for v2

### PR DESCRIPTION
**Pull request by blank3times**
Needs compiling

### CODE REVIEW

**Comment by NotAGanesh** [comment]
cherry_blossom
here is thumbnail

**Comment by NotAGanesh** [comment]
cherry blossom v2 added to MTG-Patch

**Comment by ewanhowell5195** [comment]
> cherry blossom v2 added to MTG-Patch

you can have your own fork of minecraft title generator, but please do not comment about it on here when you add someones texture to it

**Comment by ewanhowell5195** [comment]
@blank3times you have a name set on it, but the name doesnt match. this one doesnt need a name at all, it can be removed

**Comment by NotAGanesh** [comment]
> > cherry blossom v2 added to MTG-Patch
> 
> you can have your own fork of minecraft title generator, but please do not comment about it on here when you add someones texture to it

ok sorry

**Comment by blank3times** [comment]
**oops, gosh darnit**

**Comment by blank3times** [comment]
Oh this has been fixed to the best of my knowledge by the way

**Pull request merged**
